import nodemailer from 'nodemailer';
import { dbInsert, dbSelect, dbUpdate } from './supabase-rest.js';

const money=value=>`R${Number(value||0).toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const date=value=>value?new Intl.DateTimeFormat('en-ZA',{timeZone:'Africa/Johannesburg',day:'2-digit',month:'short',year:'numeric'}).format(new Date(/^\d{4}-\d{2}-\d{2}$/.test(String(value))?`${value}T00:00:00+02:00`:value)):'—';
const html=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function localMobile(value){let digits=String(value||'').replace(/\D/g,'');if(digits.startsWith('27')&&digits.length===11)digits=`0${digits.slice(2)}`;return /^0\d{9}$/.test(digits)?digits:'';}
function internationalMobile(value){const local=localMobile(value);return local?`+27${local.slice(1)}`:'';}
function render(template,variables){return String(template||'').replace(/{{\s*([a-z0-9_]+)\s*}}/gi,(_,key)=>String(variables[key]??'—'));}
function emailReady(){return ['SMTP_HOST','SMTP_PORT','SMTP_USER','SMTP_PASS','FROM_EMAIL'].every(name=>String(process.env[name]||'').trim());}
function smsReady(){return ['TWILIO_ACCOUNT_SID','TWILIO_AUTH_TOKEN','TWILIO_FROM_NUMBER'].every(name=>String(process.env[name]||'').trim());}
function whatsappReady(){return ['TWILIO_ACCOUNT_SID','TWILIO_AUTH_TOKEN','TWILIO_WHATSAPP_FROM_NUMBER'].every(name=>String(process.env[name]||'').trim());}
async function log({job,channel,subject,message,status}){await dbInsert('communication_log',{user_id:job.user_id,application_id:job.application_id||null,loan_id:job.loan_id||null,channel,direction:'outbound',subject,message,status,created_by:null}).catch(()=>{});}
function brandEmail({lender,firstName,subject,body}){const name=lender.business_name||lender.legal_name||'KredRun';return `<!doctype html><html><body style="margin:0;background:#f3f6fa;font-family:Arial,sans-serif;color:#10233f"><div style="max-width:640px;margin:auto;padding:28px 16px"><div style="background:#fff;border:1px solid #dfe7ef;border-radius:18px;padding:30px"><div style="font-size:22px;font-weight:800;color:#0d6efd">${html(name)}</div><h1 style="font-size:24px;margin:22px 0 12px">${html(subject)}</h1><p style="line-height:1.7;color:#526276">Hi ${html(firstName||'there')},</p><p style="line-height:1.7;white-space:pre-line">${html(body.replace(/^Hi\s+[^,]+,?\s*/i,''))}</p><div style="margin-top:24px;padding-top:18px;border-top:1px solid #e7edf3;color:#6a7889;font-size:12px;line-height:1.6">${html(lender.support_email||'')} ${lender.support_phone?` · ${html(lender.support_phone)}`:''}<br>Please never send your PIN, password or OTP in reply to a message.</div></div></div></body></html>`;}
async function sendEmail({job,profile,lender,subject,body}){if(!profile.email)return{channel:'email',sent:false,reason:'email_missing'};if(!emailReady())return{channel:'email',sent:false,reason:'email_not_configured'};const port=Number(process.env.SMTP_PORT||587),transport=nodemailer.createTransport({host:process.env.SMTP_HOST,port,secure:String(process.env.SMTP_SECURE||'').toLowerCase()==='true'||port===465,auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});await transport.sendMail({from:process.env.FROM_EMAIL,to:profile.email,subject,text:body,html:brandEmail({lender,firstName:profile.first_name,subject,body})});await log({job,channel:'email',subject,message:body,status:'sent'});return{channel:'email',sent:true};}
async function twilioMessage({to,from,body}){const sid=String(process.env.TWILIO_ACCOUNT_SID),auth=Buffer.from(`${sid}:${process.env.TWILIO_AUTH_TOKEN}`).toString('base64'),form=new URLSearchParams({To:to,From:from,Body:body});const response=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${encodeURIComponent(sid)}/Messages.json`,{method:'POST',headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/x-www-form-urlencoded'},body:form,signal:AbortSignal.timeout(20000)});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.message||'Twilio message failed.');return payload?.sid||null;}
async function sendSms({job,profile,subject,body}){const mobile=internationalMobile(profile.mobile);if(!mobile)return{channel:'sms',sent:false,reason:'mobile_missing'};if(!smsReady())return{channel:'sms',sent:false,reason:'sms_not_configured'};const providerReference=await twilioMessage({to:mobile,from:String(process.env.TWILIO_FROM_NUMBER),body});await log({job,channel:'sms',subject,message:body,status:'sent'});return{channel:'sms',sent:true,providerReference};}
async function sendWhatsapp({job,profile,subject,body}){const mobile=internationalMobile(profile.mobile);if(!mobile)return{channel:'whatsapp',sent:false,reason:'mobile_missing'};if(!whatsappReady())return{channel:'whatsapp',sent:false,reason:'whatsapp_not_configured'};const rawFrom=String(process.env.TWILIO_WHATSAPP_FROM_NUMBER),from=rawFrom.startsWith('whatsapp:')?rawFrom:`whatsapp:${rawFrom}`,providerReference=await twilioMessage({to:`whatsapp:${mobile}`,from,body});await log({job,channel:'whatsapp',subject,message:body,status:'sent'});return{channel:'whatsapp',sent:true,providerReference};}
async function context(job){const [templates,settings,profiles,applications,loans]=await Promise.all([dbSelect('notification_templates',{select:'*',event_type:`eq.${job.event_type}`,limit:1}),dbSelect('lender_settings',{select:'*',id:'eq.true',limit:1}),dbSelect('customer_profiles',{select:'id,first_name,last_name,email,mobile',id:`eq.${job.user_id}`,limit:1}),job.application_id?dbSelect('loan_applications',{select:'id,reference,loan_amount,loan_term_months,decision_reason',id:`eq.${job.application_id}`,limit:1}):Promise.resolve([]),job.loan_id?dbSelect('loans',{select:'id,account_number,principal_amount,outstanding_balance,next_payment_date,next_payment_amount',id:`eq.${job.loan_id}`,limit:1}):Promise.resolve([])]);return{template:templates?.[0],lender:settings?.[0]||{},profile:profiles?.[0]||{},application:applications?.[0]||{},loan:loans?.[0]||{}};}
function variables(job,c){const p=job.payload||{},a=c.application,l=c.loan,s=c.lender;return{first_name:c.profile.first_name||'',application_reference:p.reference||a.reference||'—',amount:money(p.amount??l.next_payment_amount??l.principal_amount??a.loan_amount),reason:p.reason||a.decision_reason||'',lender_name:s.business_name||s.legal_name||'the lender',support_phone:s.support_phone||'—',support_email:s.support_email||'—',loan_account:p.account_number||l.account_number||'—',due_date:date(p.due_date||l.next_payment_date),outstanding_balance:money(l.outstanding_balance)};}
export async function queueUpcomingPaymentNotifications(){
  const settings=(await dbSelect('lender_settings',{select:'day_before_reminders_enabled,due_date_reminders_enabled,reminder_days_before',id:'eq.true',limit:1}))?.[0]||{};const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Johannesburg',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),days=Math.max(1,Math.min(7,Number(settings.reminder_days_before||1))),target=new Date(`${today}T00:00:00Z`);target.setUTCDate(target.getUTCDate()+days);const before=target.toISOString().slice(0,10),dates=[];if(settings.day_before_reminders_enabled!==false)dates.push(before);if(settings.due_date_reminders_enabled!==false)dates.push(today);if(!dates.length)return{queued:0};const schedules=await dbSelect('repayment_schedule',{select:'id,loan_id,user_id,due_date,amount_due,amount_paid,status',due_date:`in.(${[...new Set(dates)].join(',')})`,status:'not.in.(paid,waived)',order:'due_date.asc',limit:500});if(!schedules?.length)return{queued:0};const loanIds=[...new Set(schedules.map(r=>r.loan_id))],loans=await dbSelect('loans',{select:'id,application_id,account_number,status,payout_status,outstanding_balance',id:`in.(${loanIds.join(',')})`}),map=new Map((loans||[]).map(r=>[r.id,r]));let queued=0;for(const row of schedules){const loan=map.get(row.loan_id),amount=Math.max(0,Number(row.amount_due)-Number(row.amount_paid));if(!loan||!['active','overdue'].includes(loan.status)||loan.payout_status!=='paid'||amount<=0)continue;const kind=row.due_date===today?'due_today':'upcoming',eventKey=`payment_upcoming:${row.id}:${row.due_date}:${kind}`;try{await dbInsert('notification_jobs',{event_key:eventKey,event_type:'payment_upcoming',user_id:row.user_id,application_id:loan.application_id||null,loan_id:loan.id,payload:{amount,due_date:row.due_date,account_number:loan.account_number,reminder_kind:kind}});queued+=1;}catch(error){if(error.databaseCode!=='23505'&&error.code!=='23505')throw error;}}return{queued};
}
export async function processNotificationJobs(limit=30){
  const jobs=await dbSelect('notification_jobs',{select:'*',status:'in.(queued,failed,partial)',attempts:'lt.5',available_at:`lte.${new Date().toISOString()}`,order:'created_at.asc',limit});let sent=0,partial=0,failed=0;
  for(const job of jobs||[]){
    try{
      const attempts=Number(job.attempts||0)+1;await dbUpdate('notification_jobs',{id:`eq.${job.id}`},{status:'processing',attempts,updated_at:new Date().toISOString()});const c=await context(job);if(!c.template)throw new Error(`Notification template ${job.event_type} is missing.`);const vars=variables(job,c),subject=render(c.template.subject_template,vars),body=render(c.template.body_template,vars),previous=job.channel_results||{},selected=[],tasks=[];
      if(c.template.email_enabled&&c.lender.notification_email_enabled!==false){selected.push('email');if(!previous.email?.sent)tasks.push(sendEmail({job,profile:c.profile,lender:c.lender,subject,body}).catch(error=>({channel:'email',sent:false,error:error.message})));}
      if(c.template.sms_enabled&&c.lender.notification_sms_enabled!==false){selected.push('sms');if(!previous.sms?.sent)tasks.push(sendSms({job,profile:c.profile,subject,body}).catch(error=>({channel:'sms',sent:false,error:error.message})));}
      if(c.template.whatsapp_enabled&&c.lender.notification_whatsapp_enabled===true){selected.push('whatsapp');if(!previous.whatsapp?.sent)tasks.push(sendWhatsapp({job,profile:c.profile,subject,body}).catch(error=>({channel:'whatsapp',sent:false,error:error.message})));}
      const fresh=tasks.length?await Promise.all(tasks):[];for(const result of fresh.filter(r=>!r.sent))await log({job,channel:result.channel,subject,message:body,status:'failed'});const combined={...previous,...Object.fromEntries(fresh.map(r=>[r.channel,r]))},successful=selected.filter(channel=>combined[channel]?.sent).length,errors=selected.filter(channel=>!combined[channel]?.sent).map(channel=>combined[channel]?.error||combined[channel]?.reason||`${channel} failed`);let status='sent';if(selected.length&&successful===0)status='failed';else if(successful<selected.length)status='partial';
      await dbUpdate('notification_jobs',{id:`eq.${job.id}`},{status,channel_results:combined,last_error:errors.join('; ').slice(0,500)||null,processed_at:status==='sent'?new Date().toISOString():null,available_at:status==='sent'?new Date().toISOString():new Date(Date.now()+Math.min(3600000,attempts*300000)).toISOString(),updated_at:new Date().toISOString()});if(status==='sent')sent+=1;else if(status==='partial')partial+=1;else failed+=1;
    }catch(error){const attempts=Number(job.attempts||0)+1;await dbUpdate('notification_jobs',{id:`eq.${job.id}`},{status:'failed',attempts,last_error:String(error.message||error).slice(0,500),available_at:new Date(Date.now()+Math.min(3600000,attempts*300000)).toISOString(),updated_at:new Date().toISOString()}).catch(()=>{});failed+=1;}
  }
  return{examined:(jobs||[]).length,sent,partial,failed,capabilities:{email:emailReady(),sms:smsReady(),whatsapp:whatsappReady()}};
}
