import { allowMethod, HttpError, requireUuid, sendError } from '../server/http.js';
import { dbSelect, requireUser } from '../server/supabase-rest.js';

const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=value=>`R${Number(value||0).toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default async function handler(req,res){
  if(!allowMethod(req,res,['GET']))return;
  try{
    const{user}=await requireUser(req);const action=String(req.query?.action||'list');
    if(action==='list'){
      const loanId=requireUuid(req.query?.loanId,'Loan');const loans=await dbSelect('loans',{select:'id,user_id',id:`eq.${loanId}`,limit:1});if(!loans?.[0]||loans[0].user_id!==user.id)throw new HttpError(404,'Loan not found.','loan_not_found');
      const letters=await dbSelect('loan_settlement_letters',{select:'id,loan_id,letter_number,settlement_date,settlement_amount,future_charge_rebate,payment_provider,generated_at',loan_id:`eq.${loanId}`,user_id:`eq.${user.id}`,order:'generated_at.desc',limit:5});return res.status(200).json({ok:true,letters:letters||[]});
    }
    if(action==='view'){
      const id=requireUuid(req.query?.id,'Settlement letter');const rows=await dbSelect('loan_settlement_letters',{select:'*',id:`eq.${id}`,user_id:`eq.${user.id}`,limit:1});const letter=rows?.[0];if(!letter)throw new HttpError(404,'Settlement letter not found.','settlement_letter_not_found');
      const[loans,lenders,profiles]=await Promise.all([dbSelect('loans',{select:'id,user_id,account_number,principal_amount',id:`eq.${letter.loan_id}`,limit:1}),dbSelect('lender_settings',{select:'business_name,legal_name,registration_number,ncr_registration_number,support_email,support_phone,physical_address',id:'eq.true',limit:1}),dbSelect('customer_profiles',{select:'id,first_name,last_name,id_number',id:`eq.${user.id}`,limit:1})]);
      const loan=loans?.[0],lender=lenders?.[0]||{},profile=profiles?.[0]||{};if(!loan||loan.user_id!==user.id)throw new HttpError(404,'Loan not found.','loan_not_found');
      res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Content-Disposition',`inline; filename="${letter.letter_number}.html"`);res.setHeader('Cache-Control','private, no-store');
      return res.status(200).send(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(letter.letter_number)}</title><style>body{font-family:Arial,sans-serif;color:#172033;margin:0;background:#f5f7fa}.page{max-width:760px;margin:40px auto;background:#fff;padding:56px;border:1px solid #e2e6ec}.head{display:flex;justify-content:space-between;gap:30px;border-bottom:2px solid #172033;padding-bottom:24px}.head h1{margin:0;font-size:25px}.muted{color:#667085}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:28px 0}.cell{border:1px solid #e4e7ec;padding:14px}.cell span{display:block;font-size:12px;color:#667085;margin-bottom:5px}.amount{font-size:24px}.sign{margin-top:45px;padding-top:18px;border-top:1px solid #e4e7ec}@media print{body{background:#fff}.page{margin:0;border:0;max-width:none}}</style></head><body><main class="page"><div class="head"><div><h1>${esc(lender.business_name||lender.legal_name||'KredRun Lender')}</h1><div class="muted">${esc(lender.legal_name||'')}</div>${lender.ncr_registration_number?`<div class="muted">NCR: ${esc(lender.ncr_registration_number)}</div>`:''}</div><div class="muted">Settlement letter<br>${esc(letter.letter_number)}<br>${esc(letter.settlement_date)}</div></div><h2>Confirmation of loan settlement</h2><p>Dear ${esc([profile.first_name,profile.last_name].filter(Boolean).join(' ')||'Client')},</p><p>This letter confirms that loan account <strong>${esc(loan.account_number||loan.id)}</strong> was settled in full on <strong>${esc(letter.settlement_date)}</strong>. The recorded outstanding balance for this loan is now <strong>R0.00</strong>.</p><div class="grid"><div class="cell"><span>Settlement payment</span><strong class="amount">${money(letter.settlement_amount)}</strong></div><div class="cell"><span>Future charges rebated</span><strong class="amount">${money(letter.future_charge_rebate)}</strong></div><div class="cell"><span>Payment provider</span><strong>${esc(letter.payment_provider||'Recorded payment')}</strong></div><div class="cell"><span>Loan account</span><strong>${esc(loan.account_number||'—')}</strong></div></div><p>No further scheduled collection should be attempted on this settled loan. If a payment was already in-flight with a payment provider before settlement confirmation, contact the lender if it later appears on your bank statement.</p><div class="sign"><strong>${esc(lender.business_name||lender.legal_name||'Lender')}</strong><br><span class="muted">${esc(lender.support_email||'')} ${esc(lender.support_phone||'')}</span></div></main></body></html>`);
    }
    throw new HttpError(400,'Unknown settlement-letter action.','invalid_action');
  }catch(error){return sendError(res,error,'Settlement letter request failed');}
}
